In [1]:
import numpy as np

In [2]:
a = [1,2,3,4]

In [3]:
a

[1, 2, 3, 4]

In [4]:
x = np.array([1,2,3,4])

arrays are similar to lists. Same results from x[1] and a[1] output is 2. Properties are mutable.

So how are they different? Arrays are faster. The larger the dataset, the more important it is to use array. There are some functional differences as we.

In [5]:
a*5

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [6]:
x*5

array([ 5, 10, 15, 20])

In [7]:
a.append(6)

In [8]:
a

[1, 2, 3, 4, 6]

In [9]:
x.append(6)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

For lists you don't have to declare your variables ahead of time. So you can add things in the background. Arrays in Python treat this differently. Needs to be defined, which is why it is faster. Set memory of set dimension with same types of things all within the same structure.

In [10]:
sum(a)

16

In [11]:
sum(x)

10

In [15]:
sum(a)/len(a)

3.2

In [16]:
sum(x)/len(x)

2.5

In [17]:
# g = np.loadtxt('grades.txt') language importing .txt in Collab

functions need to come from the numpy library, not the standard library. 

delimeter tells us how they are separated "," for example

In [18]:
# f.dim tells us the demension

In [19]:
# f.shape tells us the shape of the matrix

In [20]:
# f.size tells us how many elements

In [22]:
h = np.matrix([[3,5],
              [4,7]])

In [23]:
h

matrix([[3, 5],
        [4, 7]])

In [24]:
h*h

matrix([[29, 50],
        [40, 69]])